Katey tuit2tag
kachalmers/software-engineering-node-s2-team1-project pull request #22
Opened 2022-04-08 21:03 UTC by klalmeida

Made all the backend files for Tuit2Tag: model, daoI, controllerI, dao, controller, mongoose model, mongoose schema

The dao/controller only have create and delete operations, but we can add more if we need to.

2022-04-08 22:06 UTC, kachalmers reviewed
In server.ts, need to add the following lines:
import Tuit2TagController from "./controllers/Tuit2TagController";
const tuit2tagController = Tuit2TagController.getInstance(app);

2022-04-08 22:06 UTC, kachalmers commented on controllers/Tuit2TagController.ts
> +            app.post("api/tuit2tags", Tuit2TagController.tuit2tagController.createTuit2Tag);
This file doesn't work for me in postman. Suggested edits to line 37:

app.post("/api/tuits/:tuitID/tags/:tagID", Tuit2TagController.tuit2tagController.createTuit2Tag);

2022-04-08 22:06 UTC, kachalmers commented on controllers/Tuit2TagController.ts
> +            app.delete("api/tuit2tags/:t2tID", Tuit2TagController.tuit2tagController.deleteTuit2Tag);
This file doesn't work for me in postman. Suggested edits to line 38:

app.delete("api/tuit2tags/:t2tID", Tuit2TagController.tuit2tagController.deleteTuit2Tag);

2022-04-08 22:06 UTC, kachalmers commented on controllers/Tuit2TagController.ts
> +createTuit2Tag = (req: Request, res: Response) =>
This file doesn't work for me in postman. Suggested edits to createTuit2Tag:

    createTuit2Tag = (req: Request, res: Response) =>
        Tuit2TagController.tuit2tagDao.createTuit2Tag(req.params.tuitID, req.params.tagID)
            .then(tuit2tag => res.json(tuit2tag));

2022-04-08 22:06 UTC, kachalmers commented on controllers/Tuit2TagController.ts
> +createTuit2Tag = (req: Request, res: Response) =>
or really it would just be line 55:

        Tuit2TagController.tuit2tagDao.createTuit2Tag(req.params.tuitID, req.params.tagID)

2022-04-08 22:06 UTC, kachalmers commented on daos/Tuit2TagDao.ts
> +        // TODO: should the data type below be string or a tuit/tag object?
Suggested edits for createTuit2Tag in dao:

    createTuit2Tag = async (tuitID: string, tagID: string): Promise<Tuit2Tag> =>
        Tuit2TagModel.create({tuit: tuitID, tag: tagID});

2022-04-11 23:36 UTC, kachalmers reviewed
For mongoose/tag, could we rename "tag" to "tags" to be consistent with the rest of the mongoose folders?

2022-04-11 23:38 UTC, kachalmers requested changes
For mongoose/tag, could we rename "tag" to "tags" to be consistent with the rest of the mongoose folders?

2022-04-12 00:10 UTC, kachalmers requested changes

2022-04-12 00:10 UTC, kachalmers commented on daos/Tuit2TagDao.ts
>          Tuit2TagModel.deleteOne({tuit: tuitID, tag: tagID});
I think we should use "deleteMany" instead of "deleteOne" here for the off-chance a user adds two of the same tag to one tuit.

2022-04-12 00:10 UTC, kachalmers commented on controllers/Tuit2TagController.ts
> +            app.get("/api/tuits/:tuitID/tags/:tagID", Tuit2TagController.tuit2tagController.findTuit2TagsByTuit);
If you want to keep this path/method here, I would remove "/:tagID" from the path; we won't need the context of a tagID to find Tuit2Tags by a given tuit (we'd only need the tuitID)

2022-04-12 00:10 UTC, kachalmers commented on interfaces/Tuit2TagControllerI.ts
> +    findTuit2TagsByTuit(req: Request, res: Response): void;
Same comment at for Tuit2TagController.ts

2022-04-12 00:10 UTC, kachalmers commented on server.ts
> +import Tuit2TagController from "./controllers/Tuit2TagController";
👍  :)

2022-04-12 00:10 UTC, kachalmers commented on server.ts
> +const tuit2tagController = Tuit2TagController.getInstance(app);
👍  :)

2022-04-12 00:28 UTC, mcartervt commented on controllers/Tuit2TagController.ts
> +            app.get("/api/tuits/:tuitID/tags/:tagID", Tuit2TagController.tuit2tagController.findTuit2TagsByTuit);
I need the Dao method (findTuit2TagByTuit) for TuitController, so it just made sense to have a Controller version for Postman testing.

2022-04-12 00:31 UTC, kachalmers commented on controllers/Tuit2TagController.ts
> +            app.get("/api/tuits/:tuitID/tags/:tagID", Tuit2TagController.tuit2tagController.findTuit2TagsByTuit);
> I need the Dao method (findTuit2TagByTuit) for TuitController, so it just made sense to have a Controller version for Postman testing. But you are correct in that we only need the tuitID to find this.

Works for me! Only https://github.com/kachalmers/software-engineering-node-s2-team1-project/pull/22#discussion_r847831353 applies then

2022-04-12 19:16 UTC, mcartervt commented
Closing this PR.  Katie C. & I made the changes and will open a new request.

2022-04-12 19:16 UTC, closed without merging