Follow button implementation for back end
kachalmers/software-engineering-node-s2-team1-project pull request #29
Opened 2022-04-19 21:03 UTC by kachalmers

Added backend functionality for follow toggling.

2022-04-20 22:55 UTC, mcartervt requested changes
Tested userTogglesFollow() from FollowController via tests I added to Postman.  

Request that a Controller method be added for findUsersFollowedByUser() from the FollowDao, so it can be tested via Postman.

Otherwise it looks good!

2022-04-20 22:55 UTC, mcartervt commented on daos/FollowDao.ts
> +            .populate("followee");   // fill in information about followee
Does this need a .exec()?

2022-04-20 22:55 UTC, mcartervt commented on daos/Tuit2TagDao.ts
> +                .populate({
This is the same as in the other PR, right?

2022-04-20 22:55 UTC, mcartervt commented on daos/FollowDao.ts
> +    findUsersFollowedByUser = async (uid: string): Promise<User[]> => {
Let's make a Controller method for this, just for Postman testing purposes.

2022-04-21 02:26 UTC, kachalmers commented
> Tested userTogglesFollow() from FollowController via tests I added to Postman.
> 
> Request that a Controller method be added for findUsersFollowedByUser() from the FollowDao, so it can be tested via Postman.
> 
> Otherwise it looks good!

New commit to resolve this issue: https://github.com/kachalmers/software-engineering-node-s2-team1-project/commit/ca713df495755970e123e099de692c564619aa7a

Postman test for this controller method created in follows folder.

2022-04-21 13:10 UTC, mcartervt approved these changes
Changes are all good!

2022-04-21 15:09 UTC, klalmeida approved these changes
This looks great Katie!!

2022-04-21 15:14 UTC, merged